spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password:
    url: jdbc:mysql://localhost:3306/sign?useSSL=false&allowPublicKeyRetrieval=true
    username: root

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.springbootexample.springbootexampledp.domain